"""fix receiptcolumns

Revision ID: 8da7c57d7403
Revises: 21e5aa95d844
Create Date: 2026-06-17 20:11:11.807360

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8da7c57d7403"
down_revision: Union[str, Sequence[str], None] = "21e5aa95d844"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "receipts", sa.Column("total_detections", sa.Integer(), nullable=False)
    )
    op.add_column("receipts", sa.Column("detections", sa.JSON(), nullable=False))
    op.drop_column("receipts", "total_detection_time")
    op.drop_column("receipts", "detection")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "receipts",
        sa.Column(
            "detection",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "receipts",
        sa.Column(
            "total_detection_time", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("receipts", "detections")
    op.drop_column("receipts", "total_detections")
    # ### end Alembic commands ###
